# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Phage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('accession', models.CharField(max_length=64)),
                ('spanin_type', models.IntegerField(choices=[(0, 'embedded'), (1, 'overlapping'), (2, 'separate'), (3, 'unimolecular')])),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Spanin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.TextField()),
                ('accession', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='phage',
            name='i_spanin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_spanin', to='base.Spanin'),
        ),
        migrations.AddField(
            model_name='phage',
            name='o_spanin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='o_spanin', to='base.Spanin'),
        ),
        migrations.AddField(
            model_name='phage',
            name='u_spanin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_spanin', to='base.Spanin'),
        ),
    ]
