# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spanin',
            name='sd_sequence',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
