# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_spanin_sd_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spanin',
            name='sd_sequence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
