# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160912_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='spanin',
            name='gene_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
