# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_spanin_gene_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spanin',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spanin',
            name='type_code',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
